### ISSUE TITLE
Typings for typescript projects

### ISSUE THREAD

**Issue by andrezero** [remarkjs/remark-rehype#10]
Just starting using unified, remark & rehype in the context of a static site generator written in typescript and noticed this package is missing typings.

I just patched it with the following local `src/node_modules/remark-rehype/index.d.ts`, which is enough for my project but would be great to have complete typings for this plugin.

```
// TypeScript Version: 3.0

declare module 'remark-rehype' {
  import { Plugin } from 'unified';

  const remark2rehype: Plugin;

  export default remark2rehype;
}
```

**Comment by ChristianMurphy** [comment]
@andrezero Typings would be welcome, would you be interested in contributing them?
If you have questions or want to discuss typings in general for Unified there is a channel on Spectrum for type definitions https://spectrum.chat/unified/type-definitions feel free to reach out!

**Comment by wooorm** [comment]
I’ll close this here, so discussion can happen in one place ([spectrum](https://spectrum.chat/unified/type-definitions/missing-typings-across-plugin-community~49ee93c0-23bf-49f3-9706-2468b0760564))
