### ISSUE TITLE
outer p tag optional

### ISSUE THREAD

**Issue by sgpinkus** [remarkjs/remark-rehype#14]
### Subject of the feature
Option to remove outer p tag.

Describe your issue here.
rehype-remark will wrap HTML in a p tag. I want to not have strings wrapped in p tag optionally. I can't find an option for this.

```
var unified = require('unified');
var markdown = require('remark-parse');
var htmlStringify = require('rehype-stringify');
var remark2rehype = require('remark-rehype');

console.log(unified()
  .use(markdown)
  .use(remark2rehype)
  .use(htmlStringify)
  .processSync("hello").contents
);
```

Gives:

```
<p>hello</p>
```

### Expected behaviour
Explained above.

### Alternatives
```
...contents.replace(/^<p>/, '').replace(/<\/p>$/, '')
```

**Comment by wooorm** [comment]
Hi there @sgpinkus!

This is how Markdown works: you’ll get paragraphs, headings, and whatnot with Markdown when going to HTML.

If you’d rather “unwrap” paragraphs, you can write your own plugin (a rehype plugin is probably a good idea), that [traverses the tree and replaces `p` elements with their children](https://unifiedjs.com/learn/recipe/remove-node/)!

**Comment by sgpinkus** [comment]
Hey. 

> This is how Markdown works: you’ll get paragraphs, headings, and whatnot with Markdown when going to HTML.

Hard to see the point in it all otherwise. It's just the outer most p tag I didn't want. I pass text with absolutely no markdown markup I expected no HTML markup back.

> If you’d rather “unwrap” paragraphs, you can write your own plugin (a rehype plugin is probably a good idea)

Thanks for the suggestion. I will look into this.

**Comment by wooorm** [comment]
I understand. It’s just: the way it works, to have that outer `<p>` 🤷‍♂️ As in, you’ll have it with [CommonMark](https://spec.commonmark.org/dingus/?text=hello), [markdown-it](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22hello%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D), or here on GitHub (you can use browser dev tools to inspect):

```markdown
hello
```

Yields:

hello
