### ISSUE TITLE
Anchor tag breaks markdown

### ISSUE THREAD

**Issue by craftzdog** [remarkjs/remark-rehype#15]
I'm not sure where the actual problem resides but I report it here.

### Subject of the issue

If a given HTML has an anchor tag, it yields the broken markdown.

### Your environment

*   **OS**: macOS
*   **Packages**: 
   ```
    "rehype-parse": "^7.0.1",
    "rehype-remark": "^8.0.0",
    "remark-stringify": "^8.1.1",
    "unified": "^9.0.0"
   ```
*   **Env**: node 14.3, npm 6.14.5

### Steps to reproduce

If you have an HTML like so:

```html
<div>
  <a name="foo" />
  <span>
    <div>test1</div>
  </span>
</div>
```

Convert it into Markdown:

```js
export default function HTML2Markdown(html: string): string {
  var unified = require('unified')
  var parse = require('rehype-parse')
  var rehype2remark = require('rehype-remark')
  var stringify = require('remark-stringify')

  const c = unified()
    .use(parse)
    .use(rehype2remark)
    .use(stringify, {
      listItemIndent: '1',
      commonmark: true,
      fences: true
    })
  return (
    c
      .processSync(html)
      .toString()
}
```

### Expected behavior

You should get:

```markdown
test1
```

### Actual behavior

It outputs:

```markdown
[test1](<>)

[](<>)
```

**Comment by wooorm** [comment]
rehype is for HTML, not for XML. Your link isn’t closed, you have divs in spans, it’s all messed up!
If I open your “HTML” in a browser, I get something very similar to what you’re getting with remark/rehype:

<img width="491" alt="Screen Shot 2020-10-30 at 08 17 13" src="https://user-images.githubusercontent.com/944406/97671384-6b1eff00-1a88-11eb-853a-c72700075e1e.png">

---

Why do you have such weird HTML? Can you fix that?

**Comment by craftzdog** [comment]
Thanks for the reply.
Yes, I thought the same.
I use `remark-rehype` for supporting importing HTML files into my app as Markdown.
I got this broken HTML from my app's user who exported a note from Evernote.
So, it looks like an Evernote's bug where it generates such weird HTML..

**Comment by wooorm** [comment]
oh gosh, that’s some really weird stuff that Evernote is doing 😅

It’s indeed a bug there, you could report it with them maybe, but I’m not sure they’d fix it.
An alternative would be to do some processing with a plugin on “evernote html”? Or maybe support their [.enex](https://help.evernote.com/hc/en-us/articles/209005557) XML files (I see some projects and github that do that)? 🤷‍♂️

Anyway, not something for this project!
