### ISSUE TITLE
rollup build breaks because of mdast-util-to-hast@10.2.0 dependency

### ISSUE THREAD

**Issue by Fgruntjes** [remarkjs/remark-rehype#19]
The bug is solved in mdast-util-to-hast@11.1.1 and perfectly described in https://github.com/syntax-tree/mdast-util-to-hast/issues/55

**Comment by wooorm** [comment]
Well, we did already have the whole discussion over there. Are there new insights for opening a new issue?

**Comment by SQReder** [comment]
I suggest publishing a patched version of the package for your own and use it as a temporary replacement for `mdast-util-to-hast`

You can use [yarn `resolutions`](https://classic.yarnpkg.com/en/docs/selective-version-resolutions) section, or [`resolve.alias`](https://vitejs.dev/config/#resolve-alias) config option for Vite.js. I'm sure similar functionality should exist for webpack, but I'm too lazy to search. Also, no straightforward solution found to replace transient dependencies with NPM itself

If security doesn't bother you much, you can use [my patched](https://www.npmjs.com/package/mdast-util-to-hast-backport) version until the new release of remark-rehype

**Comment by wooorm** [comment]
fixed!
