### ISSUE TITLE
Example doesn't work, should show ESM code

### ISSUE THREAD

**Issue by teinett** [remarkjs/remark-rehype#20]
I tried the example code from readme.md:
```
var vfile = require('to-vfile')
var report = require('vfile-reporter')
var unified = require('unified')
var markdown = require('remark-parse')
var remark2rehype = require('remark-rehype')
var doc = require('rehype-document')
var format = require('rehype-format')
var html = require('rehype-stringify')

unified()
  .use(markdown)
  .use(remark2rehype)
  .use(doc)
  .use(format)
  .use(html)
  .process(vfile.readSync('example.md'), function (err, file) {
    console.error(report(err || file))
    console.log(String(file))
  })
```

It doesn't work.

Npm package to-vfile is ESM-only now: https://www.npmjs.com/package/to-vfile.

Please, update the code of the example to have it correctly written for beginners.

**Comment by wooorm** [comment]
Hi there. We‘re working through hundreds of projects. It’ll take some time. See https://github.com/unifiedjs/unified/issues/121 for more information.
I’ll close this for now, I’ll get to it when I can.
