### ISSUE TITLE
Options are not passed to mdast-util-to-hast

### ISSUE THREAD

**Issue by SunPj** [remarkjs/remark-rehype#21]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

^9.1.0

### Link to runnable example

https://codesandbox.io/s/remark-rehype-debug-4cz8v?file=/src/index.js:488-532

### Steps to reproduce

Pass a custom handler and see that it's not used 

```js
function link(h, node) {
    return h(node, 'a', {href: "/abc"}, [])
}

.use(remarkRehype, null, {handlers: {link}})

```

### Expected behavior

Custom link handler should override default one

### Actual behavior

Passed handlers are ignored

### Runtime

Node v16

### Package manager

npm v6

### OS

Linux

### Build and bundle tools

Webpack

**Comment by SunPj** [comment]
I think `options` should be passed to `mutate` method instead of `destination`

I have just compared this with rehype-remark which does opposite translation https://github.com/rehypejs/rehype-remark/blob/9.0.0/index.js

```js
function (destination, options) {
      return destination && 'run' in destination
        ? bridge(destination, options)
        : mutate(destination)
    }
```

**Comment by SunPj** [comment]
@wooorm Thanks for clarification. 

What would be a difference if we execute that passing only destination or options

`.use(remarkRehype, options)`

`.use(remarkRehype, destination)`

Will that work properly?

**Comment by SunPj** [comment]
@wooorm Thanks. Passing options worked for me, but still it's not clear that we can omit destination and pass options. I think it is worth to add that case to readme or allow passing `destination =  null && options = {some value}`

**Comment by wooorm** [comment]
Yeah I’m open to such a change. Care to work on it?

**Comment by SunPj** [comment]
@wooorm I would change `mutate(destination)` to `mutate(options)` so it's clear that we can execute this like `mutate(null, options)`. I can create PR if you like it

**Comment by wooorm** [comment]
That sounds like a braking change?
I think this fixes your use case but otherwise keeps everything working the same as before:

```diff
-settings = destination || {}
+settings = destination || options || {}
```

**Comment by SunPj** [comment]
@wooorm It looks pretty confusing to me. The contract is that method expects two arguments `F(a, b)`, it's totally fine to omit the second one. But when you call function with one argument `F(y)` you expect that you execute `F(a=y)` but not `F(a=undefined, b = y)`. Said that with current function signature I pass `options` instead of `destination` and it magically works (because in function body we assume that destination is config if there is no "run" property in it, and we pass destination to `mutate` method assuming that it is a config). 

I suggest we keep this clear and remove tricky part. 

I agree that introducing settings is good but anyway the proper method execution should look like `F(null, options)` in my case.

**Comment by wooorm** [comment]
Are you a TypeScript user?

Note that the documentation is `.use(remarkRehype[, destination][, options])`. This implies to me that the second and third parameters can be omitted completely. And I mean **omit** as not passed at all, rather than set to a nullish value.

I believe what you are thinking of would be `.use(remarkRehype, destination?, options?)`, which implies that both `destination` and `options` can be nullish.

> I suggest we keep this clear and remove tricky part.

I’m not really interested in introducing a breaking change, across several projects (remark-rehype, remark-retext, rehype-remark, rehype-retext, ...) that breaks code that’s out there, for no good reason.

> I agree that introducing settings is good but anyway the proper method execution should look like F(null, options) in my case.

I believe that that’s what my proposal allows. But your proposal breaks all existing cases.

**Comment by wooorm** [comment]
I’m also open to adding a signatures section right above `destination` in the readme. Perhaps that clears it up?:

```markdown
###### Signatures

*   `origin.use(remarkRehype, destination, options?)`
*   `origin.use(remarkRehype, options?)`
```

**Comment by SunPj** [comment]
@wooorm Sorry, I am not good at typescript. Give me some time to read through the docs. I will get back to this after. Thanks

**Comment by wooorm** [comment]
> Sorry, I am not good at typescript

No problem, not needed at all! I was just wondering if that’s where you were coming from. Usually TS users don’t like “overloads”, and these two function signatures is an instance of that, hence I was wondering if that was your background

**Comment by wooorm** [comment]
I just added support for an explicit `destination: null` to solve your expectation!

**Comment by SunPj** [comment]
Thanks @wooorm
