### ISSUE TITLE
Unable to import remark-rehype in a Deno project

### ISSUE THREAD

**Issue by dwoznicki** [remarkjs/remark-rehype#26]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

10.1.0

### Steps to reproduce

I have an `index.ts` file with the following content.

```typescript
import remarkRehype from "https://esm.sh/remark-rehype@10";
```

When I run this file with

```bash
deno run index.ts
```

I get the following errors.

```
error: TS2671 [ERROR]: Cannot augment module 'hast' because it resolves to a non-module entity.
declare module 'hast' {
               ~~~~~~
    at https://esm.sh/v92/mdast-util-to-hast@12.2.0/complex-types.d.ts:7:16

TS2694 [ERROR]: Namespace '__' has no exported member 'Options'.
      (import('https://esm.sh/v92/mdast-util-to-hast@12.2.0/lib/index.d.ts').Options | undefined)?
                                                                             ~~~~~~~
    at https://esm.sh/v92/remark-rehype@10.1.0/lib/index.d.ts:33:78

TS2694 [ERROR]: Namespace '__' has no exported member 'Options'.
  | [null | undefined, (import('https://esm.sh/v92/mdast-util-to-hast@12.2.0/lib/index.d.ts').Options | undefined)?]
                                                                                              ~~~~~~~
    at https://esm.sh/v92/remark-rehype@10.1.0/lib/index.d.ts:35:95

TS2694 [ERROR]: Namespace '__' has no exported member 'Options'.
  | [import('https://esm.sh/v92/mdast-util-to-hast@12.2.0/lib/index.d.ts').Options]
                                                                           ~~~~~~~
    at https://esm.sh/v92/remark-rehype@10.1.0/lib/index.d.ts:36:76

Found 4 errors.
```

Here is the output of `deno --version` for me.

```
deno 1.19.1 (release, x86_64-apple-darwin)
v8 9.9.115.7
typescript 4.5.2
```

### Expected behavior

I'd expect to be able to import and run remark-rehype in a Deno project.

### Actual behavior

I cannot use this module due to the errors noted above.

### Runtime

Deno

### OS

macOS

**Comment by wooorm** [comment]
I don’t get any errors:

```
$ deno --version
deno 1.23.3 (release, x86_64-apple-darwin)
v8 10.4.132.8
typescript 4.7.4
```

**Comment by dwoznicki** [comment]
Ahh, yeah, I just upgraded Deno versions and the error is gone. Nice! There must have been an issue in that version of Deno.
