### ISSUE TITLE
Add options.footnoteSymbol to API for less opinionated footnote styling

### ISSUE THREAD

**Issue by tjex** [remarkjs/remark-rehype#32]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Currently the symbol used in [`mdast-util-to-hast`](https://github.com/syntax-tree/mdast-util-to-hast/blob/7d20e86fbb0d8517497a0651dfcb229a6091a0c7/lib/footer.js#L51) gets rendered as an emoji arrow.

<img width="186" alt="Screen Shot 2023-06-01 at 15 17 29" src="https://github.com/remarkjs/remark-rehype/assets/83029642/2228737c-1f48-4ba0-8380-e4f524ca1d58">

As discussed [here](https://github.com/orgs/remarkjs/discussions/1051), the rendering of the arrow seems to depend on the host environment. On my Astro site they get rendered as an emoji arrow as above (where I only use the default markdown packages remark-gfm and smarty-pants, but here on github, footnotes get rendered as a normal text arrow  [^1].

[^1]: footnote

### Solution

As described above, the rendering behaviour due to the host environment is inconsistent. Emojis are also a very opinionated styling. I therefore think it would be great to implement a method for setting a custom symbol in place of the text arrow. For example, simply adding a different arrow for me, maintains that arrow upon rendering. 

`mdast-util-to-hast/lib/footer.js` line: 53
```diff
- children: [{type: 'text', value: '↩'}]
+ children: [{type: 'text', value: '⤴ '}]`
```

<img width="189" alt="Screen Shot 2023-06-01 at 15 09 14" src="https://github.com/remarkjs/remark-rehype/assets/83029642/a678848e-cd0e-4b69-bfea-bdb05dabfcd1">

This could look like:

`options.footerSymbol = '⤴';`

Which would simply replace the arrow symbol in `mdast-util-to-hast/lib/footer.js`

### Alternatives

Other than manually editing the `mdast-util-to-hast/lib/footer.js` file in `node_modules`, I don't think so.

**Comment by wooorm** [comment]
Yep, will get to this in a bit. It’s already implemented in [`micromark-extension-gfm-footnote`](https://github.com/micromark/micromark-extension-gfm-footnote#backlabel) and [`markdown-rs`](https://docs.rs/markdown/1.0.0-alpha.9/markdown/struct.CompileOptions.html#structfield.gfm_footnote_back_label)

> As discussed [here](https://github.com/orgs/remarkjs/discussions/1051), the rendering of the arrow seems to depend on the host environment

Hmm, it’s more: in the same way that the host may define which font is used for your website. You can use CSS to style your website. And you can use CSS for this too. See also https://css-tricks.com/text-that-sometimes-turns-to-emojis/. The fact that this happens is that GitHub uses the exact same character, but displays it differently from your site

**Comment by tjex** [comment]
excellent! and thanks for the extra info :)

**Comment by wooorm** [comment]
Solved upstream, will be here in a bit!

**Comment by tjex** [comment]
legend! thanks mate :)
