### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by Nugine** [remarkjs/remark-rehype#33]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

https://github.com/remarkjs/remark-rehype/blob/14fc569195f9ba1af504c4c276ecccd291e79922/package.json#L38-L43

### Solution

Upgrade dependencies to the latest versions

### Alternatives

None

**Comment by wooorm** [comment]
https://github.com/remarkjs/remark-rehype/releases/tag/11.0.0

You don’t need to open issues. I am already working on it.
